# Generated by Django 5.0.6 on 2024-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(default='default.pdf', upload_to='pdfs'),
        ),
    ]
